### ISSUE TITLE
Invalid benchmark download link

### ISSUE THREAD

**Issue by BonnQiam** [limbo018/DFI_homepage#1]
The benchmark download link in DFI’s introduction website (https://www.cerc.utexas.edu/utda/download/DFI/index.html) seems to be invalid. Can you update it?

**Comment by limbo018** [comment]
Hi, 




I just tried it. It looks like the link has been fixed. 




Thanks

Yibo 







                       
Original
                       
                     

From:"QIAMKING"< ***@***.*** &gt;;

Date:2023/4/25 17:56

To:"limbo018/DFI_homepage"< ***@***.*** &gt;;

CC:"Subscribed"< ***@***.*** &gt;;

Subject:[limbo018/DFI_homepage] Invalid benchmark download link (Issue #1)




 
The benchmark download link in DFI’s introduction website (https://www.cerc.utexas.edu/utda/download/DFI/index.html) seems to be invalid. Can you update it?
 
&mdash;

**Comment by BonnQiam** [comment]
Hello, 

Thank you so much for taking the time to address my concerns. I just tried it, and it seems the problem still exists. For example, if I click on the DAC'15 reuslts listed in Benchmarks, it will redirect me to Google drive. But Google drive shows that the page does not exist (refer screenshot below). Might be the reason why the link expired.

![image](https://user-images.githubusercontent.com/43517208/234496132-bf1740ba-c5c3-4954-b9c8-fbfa17b41725.png)
